### ISSUE TITLE
RT305x ESW bug

### ISSUE THREAD

**Issue by Stepa8312** [Linaro1985/padavan-ng#12]
When using an internal switch on old Ralink SoC, I noticed some problems with its operation. 
(I watched this bug on the RT5350 and RT3352)

The bug is shown under the following conditions:
1. all ports are configured in bridge (Access Point Mode)
2. a wired LAN connection is used

After the WiFI driver is reloaded, the host (web interface) of the router is unavailable. It is only available through the wireless interface.

I found a solution to similar problem in Wive-NG, but I'm not sure if it can be applied to the Padavan firmware.
>   this is workaround for internal ESW in some RT305x chips in config all lan ports in one bridge
>  for restore normal swich work after reconfigure wifi drivers
>    if [ "$CONFIG_RT_3052_ESW" != "" ]; then
> ...
>	$LOG "Reconfigure switch..."
>	/etc/scripts/config-switch.sh
>	fi
>...

**Comment by mrrdmr** [comment]
Any solution?

**Comment by Linaro1985** [comment]
Fixes in https://github.com/Linaro1985/padavan-ng/commit/c79a3303610085800a0134bf86b0d6fd513687d3
Please, check it.

**Comment by Stepa8312** [comment]
Tested on DIR620D1.
Now the web interface is available via LAN and WiFi.

**Comment by mrrdmr** [comment]
Cheers!
