### ISSUE TITLE
ASUS RT-N11P B1 support

### ISSUE THREAD

**Issue by windclimb** [Linaro1985/padavan-ng#14]
Let me speak from my heart. RT-N11P_B1 works stable with Padavan. Can you please add native support in the firmware? Thank you for your work!

Здравствуйте. Я попробовал RT-N11P_B1 с неофициальной конфигурацией для Padavan, найденной в сети. Работает очень стабильно на протяжении нескольких месяцев. Можете ли вы добавить официальную поддержку этой модели? Спасибо за ваши труды!

**Comment by Stepa8312** [comment]
Насколько я помню, с RT-N11P_B1 были некоторые проблемы.
В нем не работают светодиоды или что-то еще?

**Comment by windclimb** [comment]
Вроде не работают светодиоды и не работает IPTV STB, в остальном все стабильно и четко. Может, из-за кривой сборки.

**Comment by Linaro1985** [comment]
Скиньте все доступные материалы по данному устройству(ссылки на посты с конфигурацией, может openwrt и т.п.) - может тогда смогу добавить поддержку.

**Comment by windclimb** [comment]
https://4pda.ru/forum/index.php?showtopic=701271&view=findpost&p=65650206

https://drive.google.com/drive/folders/0B8IQoZS8air8dm5CWXNueGttelE

**Comment by Linaro1985** [comment]
Done in commit https://github.com/Linaro1985/padavan-ng/commit/2a758428d50c067873dc74acf6c0fff148fdb043
