### ISSUE TITLE
Tor: использовать конфиг вместо аргумента при запуске

### ISSUE THREAD

**Issue by dartraiden** [Linaro1985/padavan-ng#15]
https://github.com/Linaro1985/padavan-ng/blob/939f130217961958d923da2609e835ddb3b6512e/trunk/user/tor/tor.sh#L37

`/usr/sbin/tor --runasdaemon 1 --pidfile /var/run/tor.pid`

Более правильным мне кажется использовать для этого конфиг самого Tor
`RunAsDaemon 1`

**Comment by Linaro1985** [comment]
Это не очень хорошая идея, т.к. многие не разбираются в вопросе и могут просто удалить строчку с указанием pid файла.
