### ISSUE TITLE
No skins in 3.4.3.9L-100_9c61b01

### ISSUE THREAD

**Issue by mwUMK** [Linaro1985/padavan-ng#18]
In Xiaomi R3G config (with Prometheus VirtualBox) firmware does not allow skins and logos options.

The firmware that I've compiled: 3.4.3.9L-100_9c61b01

**Comment by Linaro1985** [comment]
Skins support implemented only in PROMETHEUS. As I know everything worked earlier well. Highly recommended to install PROMETHEUS again and then try enable skins.

**Comment by mwUMK** [comment]
Now I'am stared using PROMETHEUS VMware Workstation Player from http://prometheus.freize.net/.
I will write whether I succeeded.

**Comment by Linaro1985** [comment]
Padavan-ng is a [fork](https://en.wikipedia.org/wiki/Fork_(software_development)).
