### ISSUE TITLE
r8152 driver build error

### ISSUE THREAD

**Issue by Alominer** [Linaro1985/padavan-ng#20]
После обновления (2dcfea4d58af719b15a4408b3944fc0a65622342) драйвера r8152, не собирается прошивка. Куча самых разнообразных ошибок и в самом драйвере и в модулях на которые он ссылается

**Comment by Alominer** [comment]
drivers/net/usb/r8152.c:25:10: fatal error: uapi/linux/mdio.h: No such file or directory
 #include <uapi/linux/mdio.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
scripts/Makefile.build:313: recipe for target 'drivers/net/usb/r8152.o' failed
make[4]: *** [drivers/net/usb/r8152.o] Error 1
scripts/Makefile.build:443: recipe for target 'drivers/net/usb' failed
make[3]: *** [drivers/net/usb] Error 2
scripts/Makefile.build:443: recipe for target 'drivers/net' failed
make[2]: *** [drivers/net] Error 2
Makefile:990: recipe for target 'drivers' failed
make[1]: *** [drivers] Error 2
make[1]: *** Ожидание завершения заданий…

**Comment by Linaro1985** [comment]
Driver was reverted in commit: https://github.com/Linaro1985/padavan-ng/commit/ca8d6021decf5600c28ae6a4cb55307224624993

**Comment by Alominer** [comment]
Не обязательно откатывать. Можно взять коммиты [здесь](https://gitlab.com/cip-project/cip-kernel/linux-cip/commits/70752628521df94b45ed24287fdf216f9b587681/drivers/net/usb/r8152.c) и накатить на дефолтный драйвер из падавановской ветки.
Забирайте - [r8152.txt](https://github.com/Linaro1985/padavan-ng/files/2558023/r8152.txt)
