### ISSUE TITLE
TP-LINK TL-WR840N V6 issues

### ISSUE THREAD

**Issue by mpyrozhok** [Linaro1985/padavan-ng#22]
I've compiled `padavan-ng` firmware for V6 revision of wr840n. This revision has 64K bootloader, so it required minor changes in `partitions.config` file. It successfully boots, but there are some issues. This router has only one multi-colored led: green led shows activity on the second lan port, orange led shows activity on wan port with current settings. The most significant issue is that network connectivity is very unstable. It works OK for a couple of seconds after booting, but then it starts dropping packets. The link stays up the whole time, it seems to work fine for 5 seconds and then stops for the next 10. This is how it looks if I'm trying to ping router from client machine:

```PING 192.168.0.1 (192.168.0.1) 56(84) bytes of data.
64 bytes from 192.168.0.1: icmp_seq=1 ttl=64 time=0.720 ms
64 bytes from 192.168.0.1: icmp_seq=2 ttl=64 time=0.478 ms
64 bytes from 192.168.0.1: icmp_seq=3 ttl=64 time=0.249 ms
64 bytes from 192.168.0.1: icmp_seq=4 ttl=64 time=0.509 ms
64 bytes from 192.168.0.1: icmp_seq=14 ttl=64 time=0.321 ms
64 bytes from 192.168.0.1: icmp_seq=15 ttl=64 time=0.448 ms
64 bytes from 192.168.0.1: icmp_seq=16 ttl=64 time=0.289 ms
64 bytes from 192.168.0.1: icmp_seq=17 ttl=64 time=0.303 ms
64 bytes from 192.168.0.1: icmp_seq=26 ttl=64 time=0.462 ms
64 bytes from 192.168.0.1: icmp_seq=27 ttl=64 time=0.486 ms
64 bytes from 192.168.0.1: icmp_seq=28 ttl=64 time=0.472 ms
64 bytes from 192.168.0.1: icmp_seq=29 ttl=64 time=0.466 ms
64 bytes from 192.168.0.1: icmp_seq=39 ttl=64 time=0.537 ms
64 bytes from 192.168.0.1: icmp_seq=40 ttl=64 time=0.488 ms
64 bytes from 192.168.0.1: icmp_seq=41 ttl=64 time=0.474 ms
64 bytes from 192.168.0.1: icmp_seq=42 ttl=64 time=0.506 ms
```

This behavior is observed both over wifi and ethernet. Could anybody provide insights on possible origin of this problem?
[genlog.txt](https://github.com/Linaro1985/padavan-ng/files/2613637/genlog.txt)
[dmesg.txt](https://github.com/Linaro1985/padavan-ng/files/2613639/dmesg.txt)

**Comment by mpyrozhok** [comment]
Not sure exactly why, but after I've rebuilt firmware and made insignificant changes to the sourcetree, it appears to work great. Maybe it was something with my local setup, or maybe I'm missing something.

**Comment by godshades** [comment]
@mpyrozhok hi, I have 840N v5 and v6
May you share your partitions.config, or where I can find tutorial to edit this
after edit config, just follow this link is ok right ?
https://bitbucket.org/padavan/rt-n56u/wiki/EN/HowToMakeFirmware

**Comment by mpyrozhok** [comment]
@godshades `padavan-ng` has the correct `partitions.config` file merged. Just use appropriate config file and follow build instructions.

**Comment by godshades** [comment]
@mpyrozhok hi, can I use Prometheus to make firmware easier ?

**Comment by mpyrozhok** [comment]
@godshades I haven't used Premetheus for 840N v6, so I can't give a definitive answer. You can always try.

**Comment by godshades** [comment]
@mpyrozhok hi, in step 9 said Edit path to toolchain
how to edit the config file, i don't know what command

**Comment by godshades** [comment]
when using Prometheus i'm alway error, sad

**Comment by mpyrozhok** [comment]
@godshades You don't need to edit anything toolchain-related in this fork. At least on recent Debian-based distros.
- Just clone padavan-ng repository, go to the `toolchain` directory and run `build_toolchain.sh` script. After it finishes working, copy `trunk/configs/templates/tplink/tl_wr840n-v6.config` file to `trunk/.config`, make any adjustments by uncommenting/commenting config lines in `.config`, then run `trunk/build_firmware.sh` script. If everything finishes successfully there will be a `TL_WR840N-V6_3.4.3.9L-100.bin` file in `trunk/images` directory.
- Next you will need to pad this file with 64K boot-loader (you can use actual boot-loader extracted from the stock firmware, or a 64K block of zeroes, because this area is not flashed while updating via TFTP, it is required only for boot loader to find firmware at the correct offset). Create a 64K file filled with zeros by running `dd if=/dev/zero of=padding bs=512 count=128`. Then concatenate this file with your `TL_WR840N-V6_3.4.3.9L-100.bin` by running `cat padding TL_WR840N-V6_3.4.3.9L-100.bin > tp_recovery.bin`. This file `tp_recovery.bin` could be flashed via TFTP using standard TP-LINK recovery procedure. TFTP server ip address has to be 192.168.0.66.

After you've flashed Padavan firmware via TFTP, it will be possible to flash new firmware updates using web interface. These updates do not require padding to be flashed.
Here is the firmware binary for TL-WR840N-V6 I've created using current repository state:  [tp_recovery.zip](https://github.com/Linaro1985/padavan-ng/files/3342342/tp_recovery.zip). If you'd decide to use it, know that  I'm not holding any responsibility in case you accidentally brick your router with it.

**Comment by godshades** [comment]
@mpyrozhok hi, in my country 840n have 8mb flash ram, how I can change config to match that

**Comment by mpyrozhok** [comment]
@godshades You'd probably want to change your `trunk/configs/boards/TPLINK/TL_WR840N-V6/partition.config` to something like [partition.zip](https://github.com/Linaro1985/padavan-ng/files/3342608/partition.zip). This is only if the bootloader for 8MB version is of the same size as for 4MB. If it is 128K then you probably need to simply use `trunk/configs/boards/TPLINK/pt_tplink_8m.config` or  `trunk/configs/boards/TPLINK/pt_tplink_8m_bigstor.config` and pad your firmware with 128K prefix.

**Comment by godshades** [comment]
@mpyrozhok how I can edit board.mk, i'm using 'vi board.mk' then edit but when save it say read only, cannot save

**Comment by mpyrozhok** [comment]
@godshades `chmod 0644 board.mk`? Make sure that you are the owner of this file and that it is writable.

**Comment by godshades** [comment]
@mpyrozhok sr for bother you again
after I flash tp_recovery.bin via TFTP, my router green led is alway tick and I can't ping to anything
I try stock firmware but still the same :(
And if you free can you help me build other version for 840n-v5, I alway error and can't do it myself :(

**Comment by mpyrozhok** [comment]
@godshades did you create this `tp-recovery.bin` file yourself, or you've used the one I've attached earlier? What boot size did you use? When you're trying to flash the stock firmware, are you sure that router requests and reads file from TFTP server? Which stock firmware file do you use?
Here is tp_recovery for V5: [tp_recovery.zip](https://github.com/Linaro1985/padavan-ng/files/3398412/tp_recovery.zip)

**Comment by godshades** [comment]
![image](https://user-images.githubusercontent.com/12244851/61382890-ca7aef00-a8d7-11e9-9155-11b1bae36c64.png)
hi, after flash your .zip, my router just light up 1 time then turn off :D 
Do you know how to copy your zip to vmware prometheus
I want try this script flash

**Comment by mpyrozhok** [comment]
@godshades what do you mean "turn off". Does it reboot infinitely? If not then maybe it works? Have you tried connecting to it via ethernet? It doesn't matter if you've flashed it with prometheus or via tftp, it does the same thing. The actual flashing is performed by boot loader. Are both of your routers bricked at this point?

**Comment by godshades** [comment]
@mpyrozhok I tried flash 3 firmware: padavan, openwrt, stock
All of them make my router boot loop :D 
What I can try next bro, if you have facebook or something for easier chatting please tell me :D

**Comment by mpyrozhok** [comment]
@godshades ok, so the best option for you now is to reflash them back to stock firmware. You need to get appropriate stock firmware files from tp-link website and cut first 512 bytes out of them by executing `dd if=stock.bin of=tp_recovery.bin bs=512 skip=1`. Then you can flash `tp_recovery.bin` via TFTP. I'm afraid that further attempts to flash padavan without having a console and a flash programmer are too risky. It seems that your hardware is different from mainstream, or it may be something else. Please try to flash stock firmware and tell if it worked for you.

**Comment by godshades** [comment]
@mpyrozhok wow, after try many times, now padavan working
before I open on chrome and can't go to admin page
last time I try open on edge and it's working
thanks you so much :D
last question: now can I direct flash via web for openwrt ?
and for weak device padavan or openwrt better :D

**Comment by mpyrozhok** [comment]
@godshades openwrt developers do not recommend it to use on devices with flash size less than 16MB, so padavan is probably the best choice for 840n. I'm not sure what you meant by "can I direct flash via web for openwrt". If you want to flash openwrt via padavan's web-interface, then I can't say anything useful, because I haven't tried to flash anything other than padavan firmware from its web interface.

**Comment by godshades** [comment]
@mpyrozhok ok, I will stay with padavan, thank you again
