### ISSUE TITLE
Toolchain не собирается

### ISSUE THREAD

**Issue by neuro18** [Linaro1985/padavan-ng#24]
Добрый день.

После коммитов от Nov 29, 2018 перестал собираться тулчейн.
ОС - Debian 9 32-bit.

Лог:
...
checking for bash... /bin/bash
checking for GNU bash >= 3.1... yes
checking for absolute path to gawk... /usr/bin/gawk
checking for GNU awk... yes
checking for make... /usr/bin/make
checking for GNU make >= 3.81... yes
**checking for libtool...
checking for GNU libtool >= 2.4... no
configure: error: Required tool not found: libtool**

Судя по ошибке, тулчейн не видит наличие пакета libtool, хотя в системе он установлен (и раньше подобной ошибки не возникало):

`dpkg-query -l | grep libtool`:

ii  libltdl-dev:i386              2.4.6-2                        i386         System independent dlopen wrapper for GNU libtool
ii  libltdl7:i386                 2.4.6-2                        i386         System independent dlopen wrapper for GNU libtool
ii  libtool                       2.4.6-2                        all          Generic library support script

**Comment by Linaro1985** [comment]
sudo apt-get install libtool-bin
