### ISSUE TITLE
Xiaomi Mi router 3 configuration not working 

### ISSUE THREAD

**Issue by sudtanj** [Linaro1985/padavan-ng#29]
i use prometheus beta to compile padavan-ng but got message error when tried to build firmware. the toolchain process is successful though.

![error](https://user-images.githubusercontent.com/17475015/50380536-ad14d800-069c-11e9-9c58-1ee1231ef71f.png)

i can't really get any information further than above screenshot because i not really know about the source code and many of the note are in russian.

**Comment by Linaro1985** [comment]
You can build firmware manualy, withou PROMETHEUS. For a example:
cd ~/
git clone https://github.com/Linaro1985/padavan-ng.git padavan-ng
cd padavan-ng/toolchain
sudo -s
./build_toolchain.sh
cd ../trunk
cp configs/templates/xiaomi/mi-3.config .config
./clear_tree.sh
./build_firmware.sh

You can found firmware in padavan-ng/trunk/images if build is ok.

P.S.
Packages needed for compilation:
apt update && apt -y install autoconf automake autopoint bison build-essential flex gawk gettext git gperf libtool pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev texinfo python-docutils help2man libncurses5-dev netcat sudo libtool-bin

**Comment by blueveryday** [comment]
I find the right way ,
we have to run the start.sh by root .
and then , no errors up again.

**Comment by blueveryday** [comment]
> You can build firmware manualy, without PROMETHEUS. For a example:
> cd ~/
> git clone https://github.com/Linaro1985/padavan-ng.git padavan-ng
> cd padavan-ng/toolchain
> sudo -s
> ./build_toolchain.sh
> cd ../trunk
> cp configs/templates/xiaomi/mi-3.config .config
> ./clear_tree.sh
> ./build_firmware.sh
> 
> You can found firmware in padavan-ng/trunk/images if build is ok.
> 
> P.S.
> Packages needed for compilation:
> apt update && apt -y install autoconf automake autopoint bison build-essential flex gawk gettext git gperf libtool pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev texinfo python-docutils help2man libncurses5-dev netcat sudo libtool-bin

Why did we had to use root to build the chaintool ?

**Comment by godshades** [comment]
@blueveryday hi I'm new linux system
the way to run by root is: install root then sudo su then ./start.sh right?
