### ISSUE TITLE
Please add support for TP-Link Archer mr200

### ISSUE THREAD

**Issue by sensegsm** [Linaro1985/padavan-ng#3]
I have installed padavan firmware for TP-Link Archer C20.v1 into TP-Link Archer mr200.v1 and work perfect, except modem that can not be set. This is firmware:
[PadavanTL_C20-V1_3.4.3.9L-100.zip](https://github.com/Linaro1985/padavan-ng/files/2209718/PadavanTL_C20-V1_3.4.3.9L-100.zip)

Please help us, would be a good option for our routers. Thanks for good work.

**Comment by Linaro1985** [comment]
Is it supported by openwrt?

**Comment by maurerr** [comment]
yes it is 
https://wiki.openwrt.org/toh/tp-link/archer-mr200
https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=c8043137bbd323b1490ae8613eab915ba9c138ee

**Comment by Linaro1985** [comment]
Done in commit https://github.com/Linaro1985/padavan-ng/commit/934a7d834339945df0a7a559050f78cdecb8d1b2
Could you check it?

**Comment by maurerr** [comment]
will do it this weekend.
thanks for your work !

**Comment by EgidijusL** [comment]
How to install it? Shows an error, maybe I missed something.

**Comment by maurerr** [comment]
ehe - you have to do it from openwrt procedure - which is kind of prone to errors - i bricked my device really bad - i had to write the uboot via raspberry pi and jtag cables
https://openwrt.org/toh/tp-link/archer-mr200#oem_installation_using_the_tftp_method

**Comment by EgidijusL** [comment]
Then I'll stay with tp-link. Maybe it will work well
