### ISSUE TITLE
Не создавать пользователя dnscrypt, если прошивка собирается без DNSCrypt

### ISSUE THREAD

**Issue by dartraiden** [Linaro1985/padavan-ng#36]
https://github.com/Linaro1985/padavan-ng/blob/9646d21552010ecc92718cefebdef874e1178f76/trunk/user/shared/shutils.c#L207

https://github.com/Linaro1985/padavan-ng/blob/9646d21552010ecc92718cefebdef874e1178f76/trunk/user/shared/shutils.c#L220

https://github.com/Linaro1985/padavan-ng/blob/9646d21552010ecc92718cefebdef874e1178f76/trunk/user/shared/shutils.c#L242

Есть ли возможность обернуть это в `#if defined(APP_DNSCRYPT)`, чтобы не создавать пользователя без реальной необходимости?

**Comment by Stepa8312** [comment]
Если быть точнее, строки надо завернуть в
#ifdef CONFIG_FIRMWARE_INCLUDE_DNSCRYPT

**Comment by Linaro1985** [comment]
https://github.com/Linaro1985/padavan-ng/commit/db04302857645cd399de5ed0208da33a996df240
