### ISSUE TITLE
Broken build for DIR300B7 target

### ISSUE THREAD

**Issue by Stepa8312** [Linaro1985/padavan-ng#37]
`../src/crypto/crypto_openssl.c:10:10: fatal error: openssl/opensslv.h: No such file or directory
 #include <openssl/opensslv.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:1981: recipe for target '../src/crypto/crypto_openssl.o' failed
make[3]: *** [../src/crypto/crypto_openssl.o] Error 1
make[3]: Leaving directory '/opt/padavan-ng/trunk/user/wpa_supplicant/wpa_supplicant'
`

Should wpa_supplicant be builded for devices with 4MB of flash memory?

**Comment by Linaro1985** [comment]
https://github.com/Linaro1985/padavan-ng/commit/aa8f0d9bf50e46bf40aa8b713e36f29b8f797065
