### ISSUE TITLE
Updating firmware rewrites /etc/storage

### ISSUE THREAD

**Issue by neuro18** [Linaro1985/padavan-ng#4]
Добрый день.

Роутер ASUS RT-N56U rev A, с установленной прошивкой из репозитария Linaro/padavan-fw, бранч rework, собранная до коммита 4281970 от Июнь 28, 2018.

Собрал прошу из репозитария Linaro/padavan-ng, до последнего актуального коммита 6ccf2bc от Июль 12, 2018. Прошил. Потерял содержимое всего etc/storage, который, судя по всему, просто перезаписался заново сгенерированными файлами по-умолчанию. Потерял кучу кастомных скриптов, все сертификаты, закрытые ключи HTTPS, OpenVPN и OpenSSH, все кастомные конфиги и логины/пароли для кучи внешних сервисов. Все это накапливалось годами, восстановить по памяти нереально. Настолько привык к безопасности обновления падавановской прошивки, что отвык делать бекапы настроек. Нашел только самые древние и давно не актуальные.

Вопрос: в чем может быть причина, и как жить дальше?

**Comment by neuro18** [comment]
Конец света отменяется :). Простая заливка проши из упомянутого выше репозитария Linaro/padavan-fw бранч rework возвращает "потертый" /etc/storage на место. Вы поменяли разметку флеша для указанной модели с переходом на padavan-ng?

**Comment by Linaro1985** [comment]
Вполне такое может быть. Скиньте пожалуйста таблицу разделов, которая у вас была на старой поошивке. Я сверю.

**Comment by neuro18** [comment]
Да, таблицы разделов отличаются.

Для ASUS RT-N56U rev. A:

1) Репозитарий Linaro/padavan-fw бранч rework (подразумевается оригинальная падавановская разметка, так?), последний коммит на момент написания сообщения:

```kernel: ralink flash device: 0x1000000 at 0x1c000000
kernel: Ralink SoC physically mapped flash: Found 1 x16 devices at 0x0 in 16-bit bank. Manufacturer ID 0x0000c2 Chip ID 0x0022cb
kernel: Ralink SoC physically mapped flash: Found an alias at 0x800000 for the chip at 0x0
kernel: Amd/Fujitsu Extended Query Table at 0x0040
kernel:   Amd/Fujitsu Extended Query version 1.1.
kernel: number of CFI chips: 1
kernel: Creating 7 MTD partitions on "Ralink SoC physically mapped flash":
kernel: 0x000000000000-0x000000030000 : "Bootloader"
kernel: 0x000000030000-0x000000040000 : "Config"
kernel: 0x000000040000-0x000000050000 : "Factory"
kernel: 0x000000050000-0x0000001683d0 : "Kernel"
kernel: 0x0000001683d0-0x0000007f0000 : "RootFS"
kernel: 0x0000007f0000-0x000000800000 : "Storage"
kernel: 0x000000050000-0x000000800000 : "Firmware_Stub"
```
2) Репозитарий Linaro/padavan-ng, последний коммит на момент написания сообщения:

```kernel: ralink flash device: 0x1000000 at 0x1c000000
kernel: Ralink SoC physically mapped flash: Found 1 x16 devices at 0x0 in 16-bit bank. Manufacturer ID 0x0000c2 Chip ID 0x0022cb
kernel: Ralink SoC physically mapped flash: Found an alias at 0x800000 for the chip at 0x0
kernel: Amd/Fujitsu Extended Query Table at 0x0040
kernel:   Amd/Fujitsu Extended Query version 1.1.
kernel: number of CFI chips: 1
kernel: 7 mtdsplitter partitions found on MTD device Ralink SoC physically mapped flash
kernel: Creating 7 MTD partitions on "Ralink SoC physically mapped flash":
kernel: 0x000000000000-0x000000030000: "Bootloader"
kernel: 0x000000030000-0x000000040000: "Config"
kernel: 0x000000040000-0x000000050000: "Factory"
kernel: 0x000000050000-0x000000168530: "Kernel"
kernel: 0x000000168530-0x0000007e0000: "RootFS"
kernel: mtd: device 4 (RootFS) set to be root filesystem
kernel: 0x0000007e0000-0x000000800000: "Storage"
kernel: 0x000000050000-0x000000800000: "Firmware_Stub"
```
Пока оставил padavan-ng, залив бекап /etc/storage из padavan-fw. Вообще такие вещи надо делать осторожнее и предупреждая заранее. Чуть не поседел. Представляю что с теми, кто мог накатывать прошу на продакшене по удаленке.

**Comment by Linaro1985** [comment]
Я понимаю вас, но нужно делать бэкапы настроек. Мало ли чего в жизни бывает) Гроза, скачки напряжения и т. п. Пока таблицу разделов оставлю как есть. Так как, возможно, уже есть люди, которые перешли на новый репозиторий и все настроили. Если поменяю, то настройки слетят уже у них.

**Comment by DyGyg** [comment]
А эта проблема касается ВСЕХ роутеров? или только именно ASUS RT-N56U?
