### ISSUE TITLE
UPnP not working on Mi 3G

### ISSUE THREAD

**Issue by Cherbet** [Linaro1985/padavan-ng#46]
UPnP not working on Mi 3G, games and torrent says "Port closed".

**Comment by Linaro1985** [comment]
Fixes in https://github.com/Linaro1985/padavan-ng/commit/357d22e4d76e737b0c0536d7a684d61ffb9da3ac
Please, check it.

**Comment by Cherbet** [comment]
Okay, i check it on this weekend

**Comment by Cherbet** [comment]
> 
> 
> Fixed in [357d22e](https://github.com/Linaro1985/padavan-ng/commit/357d22e4d76e737b0c0536d7a684d61ffb9da3ac)
> Please, check it.

Maked a build and tested on last commit, all works great and upnp too(I checked miniupnpd version on openwrt, and it was 2.1 too, where is work great too), thank u soo much.
