### ISSUE TITLE
Support of the openvpn lz4 through the external liblz4 library

### ISSUE THREAD

**Issue by alexeys85** [Linaro1985/padavan-ng#5]
This is a makefile for building the library:
```makefile
SRC_NAME=lz4-1.8.2

all:
	$(MAKE) -j$(HOST_NCPU) -C $(SRC_NAME) PREFIX=$(STAGEDIR)

clean:
	if [ -f $(SRC_NAME)/Makefile ] ; then \
		$(MAKE) -C $(SRC_NAME) clean ; \
	fi ; \

install:
	$(MAKE) -C $(SRC_NAME) install PREFIX=$(STAGEDIR) DESTDIR=""

romfs:
	cp -fP $(DESTDIR)/lib/liblz4.so* $(ROMFSDIR)/lib
```
And these are additional configure flags for openvpn:
```makefile
LZ4_CFLAGS="-I$(STAGEDIR)/include" \
LZ4_LIBS="-L$(STAGEDIR)/lib -llz4" \
```
Well, the benefit of such an approach is that you don't need to patch openvpn configure scripts for the lz4 support, just unpack sources and build.
But the drawback is an additional 100 kB of space in rom.

**Comment by Linaro1985** [comment]
> But the drawback is an additional 100 kB of space in rom.
This is problem. So I don't want change it.
