### ISSUE TITLE
Is configuration transfer Xiaomi Mi3 → Mi 3G possible?

### ISSUE THREAD

**Issue by iav** [Linaro1985/padavan-ng#51]
Can i safely restore backup configuration from Xiaomi Mi3 on Xiaomi Mi 3G?
If not — what is the safest way to do it?

**Comment by Cherbet** [comment]
I think you can

**Comment by iav** [comment]
I dig into downloaded config Storage_MI-3.tbz and see

1. generic inadyn.conf — no my settings, that I see in GUI
2. I not found settings I do in Adwanced → WAN → IPv6 (http://192.168.1.1/Advanced_IPv6_Content.asp)

**Comment by Linaro1985** [comment]
It's recommended to apply settings from scratch. Transfer of a configuration between different devices will  not work correctly.

**Comment by iav** [comment]
@Linaro1985 , should I fill separate issue for what I write in previos message — or it's ok, no issies, just as planned?
