### ISSUE TITLE
MT7628 kernel panic

### ISSUE THREAD

**Issue by B1oHazard** [Linaro1985/padavan-ng#52]
После дня-двух работы рандомно падает ядро с ошибкой
`BUG: scheduling while atomic: RtmpMlmeTask/133/0x00000100`
Проблема в драйвере для mt7628, собирал раньше его в OpenWRT и ядро так же вываливалось. Подключиться новым устройствам после этого нельзя, а старые работают с большой потерей пакетов и задержкой, если отключить - заново уже не подключится. Девайс TP-Link WR841N-V13. Есть ли варианты как нибудь пофиксить это дело?

**Comment by mrrdmr** [comment]
Попробуйте собрать на gcc 6.5.

**Comment by B1oHazard** [comment]
> Попробуйте собрать на gcc 6.5. Наблюдал такое поведение с RT5350.

Сейчас работает W841N V13 на MT7628 и A5-V11 на RT5350 собранные на gcc 7.4 на последнем срезе, аптайм 4 дня без крашей. Но как раз эти 4 дня нету двух клиентов на точках доступа, возможно проблема в них. Через пару дней проверю закономерность крашей с присутствием этих клиентов, если будут проблемы то соберу на gcc 6.5 и буду дальше наблюдать. Спасибо.

**Comment by B1oHazard** [comment]
В итоге только что снова крашнулся MT7628, значит проблема таки не в клиентах. Собираю последний срез на gcc 6.5

**Comment by B1oHazard** [comment]
Собирал на gcc 6.5, потом на linaro-gcc-4.9, крашится так же. Похоже проблема или в девайсе, или в драйвере.

**Comment by B1oHazard** [comment]
Проблема похоже в калибровках радиомодуля от TP-Link. Вырезал EEPROM из дампа Xiaomi MI-Nano и залил себе через Breed, в нем же поменял MAC на свой. Подправил конфиг на стандартную разметку MT7628 (у TP-Link используется своя разметка) и собрал прошивку. Вместо своих стандартных 45-47 мегабит по воздуху на калибровках TP-Link (на стоке, на OpenWRT с проприетарным драйвером, и на Padavan всегда было 45-47, больше никак) теперь выходит ~65 на калибровках Xiaomi или Zyxel. Возможно драйвер и крашится из-за косяка от TP-Link, буду наблюдать дальше, но пока вроде как стабильно всё работает.

**Comment by Linaro1985** [comment]
Лучше дамп от zyxel использовать. C Xiaomi вечно какие-то проблемы всплывают.

**Comment by B1oHazard** [comment]
> Лучше дамп от zyxel использовать. C Xiaomi вечно какие-то проблемы всплывают.

Вчера их сравнивал и тоже остановился на Zyxel Start 2, вроде как немного лучше работает чем от Xiaomi.

**Comment by B1oHazard** [comment]
В общем краши никуда не делись после всех манипуляций, куда копать дальше не знаю. Вроде же много людей на TP-Link и Xiaomi MI-Nano используют этот драйвер для MT7628, а проблема такая только у меня :)

**Comment by mrrdmr** [comment]
А если собрать без SingleSKU?

**Comment by B1oHazard** [comment]
Как буду дома - разберу binwalk сток от Zyxel Start 2, в стоке ж можно конфиг тот выдрать?

**Comment by mrrdmr** [comment]
Если разбирается, то, конечно, да. Если прошивка собрана с SingleSKU. А так тут в конфиге HC5661A есть для FCC региона, соответственно в настройках 2.4G нужно выбирать страну из FCC.

**Comment by B1oHazard** [comment]
Похоже ни в каких прошивках кроме той что вы написали и не собирают драйвер с SingleSKU, пока что собрал с CONFIG_RT_DEBUG и накинул патч связанный с RtmpMlme из PandoraBox и убрал в драйвере выпадение в CCK и OFDM, буду смотреть. Пока что 12 часов аптайма.

**Comment by B1oHazard** [comment]
Уже неделю полёт вроде как нормальный, крашей не наблюдаю. Были применены 2 патча, вот ссылки на них вдруг у кого будет такая же проблема.
https://github.com/zhoutao0712/mtkwrt/commit/2a9d5d5eb1590c539f2dd0fcae7e57fc840f9e81
https://github.com/aboutboy/driver/blob/master/mt7628/patches/0112-fix-xiaomi6-iot-crash.patch
