### ISSUE TITLE
Куда вписать правила для ip6tables?

### ISSUE THREAD

**Issue by iav** [Linaro1985/padavan-ng#53]
Куда можно вписать дополнительные правила для ip6tables?
Сейчас посде настройки туннеля через tunnelbroker вся внутренняя сеть оказывается открытой для мира по IPv6.

**Comment by J0s3f** [comment]
You can add them in Customization/Scripts/Run After Firewall Rules Restarted:

But at least on my routers, all ipv6 ports are closed for incoming traffic unless I add manual rules!

**Comment by iav** [comment]
For tunnel too?

**Comment by B1oHazard** [comment]
> For tunnel to tunnelbroker too? With 6in4?

Да, должно работать. Для 6in4 создаётся устройство sit1.

**Comment by J0s3f** [comment]
> For tunnel to tunnelbroker too? With 6in4?

Yes I use a Tunnel from tunnelbroker.net. The tunnel is set up using the Webinterface of the firmware. All ports of internal devices are blocked from outside by default, I have rules to allow some access in the "Run After Firewall Rules Restarted" script.

**Comment by iav** [comment]
Thank you!
