### ISSUE TITLE
Update dnscrypt-proxy

### ISSUE THREAD

**Issue by WaterFlex** [Linaro1985/padavan-ng#56]
Can you upgrade [dnscrypt-proxy](https://github.com/jedisct1/dnscrypt-proxy)?

**Comment by Linaro1985** [comment]
This dnscrypt-proxy version written on go language which does not supported and requires more hardware resources. I think best solution to replace dnscrypt-proxy with stubby (DoT technology) in the future.

**Comment by WaterFlex** [comment]
I got it. Thanks you.
