### ISSUE TITLE
Add RT3352 support

### ISSUE THREAD

**Issue by Stepa8312** [Linaro1985/padavan-ng#7]
What about adding support for RT3352?
[RT3352_EEPROM.zip](https://github.com/Linaro1985/padavan-ng/files/2243581/RT3352_EEPROM.zip)

This patch adds eeprom:
`---
 trunk/proprietary/rt_wifi/rtsoc/2.7.X.X/rt2860v2/include/iface/rtmp_rbs.h | 2 +-
 trunk/vendors/Mediatek/Makefile                                           | 7 +++++++
 trunk/vendors/Mediatek/RT3352_AP_2T2R-1LNA_V12.bin                        | Bin 0 -> 512 bytes
 trunk/vendors/Mediatek/RT3352_AP_2T2R_V11.bin                             | Bin 0 -> 513 bytes
 4 files changed, 8 insertions(+), 1 deletion(-)
 create mode 100644 trunk/vendors/Mediatek/RT3352_AP_2T2R-1LNA_V12.bin
 create mode 100644 trunk/vendors/Mediatek/RT3352_AP_2T2R_V11.bin

diff --git a/trunk/proprietary/rt_wifi/rtsoc/2.7.X.X/rt2860v2/include/iface/rtmp_rbs.h b/trunk/proprietary/rt_wifi/rtsoc/2.7.X.X/rt2860v2/include/iface/rtmp_rbs.h
index 54cd191..1dc18cb 100644
--- a/trunk/proprietary/rt_wifi/rtsoc/2.7.X.X/rt2860v2/include/iface/rtmp_rbs.h
+++ b/trunk/proprietary/rt_wifi/rtsoc/2.7.X.X/rt2860v2/include/iface/rtmp_rbs.h
@@ -71,7 +71,7 @@
 #endif /* CONFIG_RALINK_RT3662_2T2R */
 
 #if defined(CONFIG_RALINK_RT3352_2T2R)
-#define EEPROM_DEFAULT_FILE_PATH                     "/etc_ro/Wireless/RT3352_AP_2T2R-4L_V12.BIN"
+#define EEPROM_DEFAULT_FILE_PATH                     "/etc_ro/Wireless/RT3352_AP_2T2R.bin"
 #endif /* CONFIG_RALINK_RT3352_2T2R */
 
 #if defined(CONFIG_RALINK_RT5350_1T1R)
diff --git a/trunk/vendors/Mediatek/Makefile b/trunk/vendors/Mediatek/Makefile
index 1d74e14..0ad6ee7 100644
--- a/trunk/vendors/Mediatek/Makefile
+++ b/trunk/vendors/Mediatek/Makefile
@@ -103,6 +103,13 @@ endif
 ifeq ($(CONFIG_RALINK_RT5350_1T1R),y)
 	$(ROMFSINST) /etc_ro/Wireless/RT5350_AP_1T1R_V1_0.bin
 endif
+ifeq ($(CONFIG_RALINK_RT3352_2T2R),y)
+ifeq ($(CONFIG_RT2860V2_AP_RTMP_INTERNAL_TX_ALC),y)
+	$(ROMFSINST) RT3352_AP_2T2R_V11.bin /etc_ro/Wireless/RT3352_AP_2T2R.bin
+else
+	$(ROMFSINST) RT3352_AP_2T2R-1LNA_V12.bin /etc_ro/Wireless/RT3352_AP_2T2R.bin
+endif
+endif
 ifdef CONFIG_RT5592_AP
 ifeq ($(CONFIG_RT5592_AP_EP_SUPPORT),y)
 	$(ROMFSINST) /etc_ro/Wireless/RT5592EP_PCIe_2T2R_5G_V1_4.bin
diff --git a/trunk/vendors/Mediatek/RT3352_AP_2T2R-1LNA_V12.bin b/trunk/vendors/Mediatek/RT3352_AP_2T2R-1LNA_V12.bin
new file mode 100644
index 0000000..76285fb
Binary files /dev/null and b/trunk/vendors/Mediatek/RT3352_AP_2T2R-1LNA_V12.bin differ
diff --git a/trunk/vendors/Mediatek/RT3352_AP_2T2R_V11.bin b/trunk/vendors/Mediatek/RT3352_AP_2T2R_V11.bin
new file mode 100644
index 0000000..681bd13
Binary files /dev/null and b/trunk/vendors/Mediatek/RT3352_AP_2T2R_V11.bin differ
--`

**Comment by Stepa8312** [comment]
Also there is a config for DIR620 Rev.D1 (Basically I copied everything from DIR320)
[config.zip](https://github.com/Linaro1985/padavan-ng/files/2243593/config.zip)

**Comment by Stepa8312** [comment]
But there are two issues:
1. Wifi/Power LEDs turn off after the router is loaded
2. RAM / SPI frequency not detected

**Comment by Stepa8312** [comment]
RAM/SPI frequency is not detected because sysboard_sysclk is not defined in arch/mips/rt2880/init.c
![rt3352_clock](https://user-images.githubusercontent.com/41925859/43563608-9b21ad94-962b-11e8-9e4a-14de605b9762.png)

Most likely there should be a divider 1: 3
[0001-add-OCPSYS-frequency-for-RT3352-target.patch.zip](https://github.com/Linaro1985/padavan-ng/files/2252196/0001-add-OCPSYS-frequency-for-RT3352-target.patch.zip)

**Comment by Stepa8312** [comment]
Final config files for DIR620D1
[dir620d1.tar.gz](https://github.com/Linaro1985/padavan-ng/files/2257231/dir620d1.tar.gz)

**Comment by Stepa8312** [comment]
Looks like I found the problem with RT3352 GPIO - PIODIR register are reset to default value 0x000000 (configured as input). Therefore GPIO 0..23 does not control the LEDs/USB power.

**Comment by Linaro1985** [comment]
Hi! Unfortunately, I have no dlink device on hands to check work. I will try to study sources for RT3352 support. In general, I not against.

**Comment by Stepa8312** [comment]
I conducted further research:
GPIO is turned off after executing the line
**ifconfig (IFNAME_MAC, IFUP, NULL, NULL);**
in file: trunk / user / rc / net_lan.c (function init_bridge).

Any ideas how to get around this bug?

**Comment by Stepa8312** [comment]
Fixed config:
[dir620.tar.gz](https://github.com/Linaro1985/padavan-ng/files/2277629/dir620.tar.gz)

I added **init_gpio_led_buttons ()** to **trunk / user / rc / rc.c** after **init_bridge (is_ap_mode)**.
It seems that all the LEDs / USB work correctly.

**Comment by mrrdmr** [comment]
Thanks! It also fixed LED issue on RT5350 device. init_gpio_led**s**_buttons ()

**Comment by Linaro1985** [comment]
https://github.com/Linaro1985/padavan-ng/commit/487eb3b748a63d0abc33d14f8892f11b77aef0bb

**Comment by Stepa8312** [comment]
I checked the build on freshly install Linux Mint 19.1

**Comment by Linaro1985** [comment]
Thx.
