### ISSUE TITLE
Read WAN/LAN mac from EEPROM

### ISSUE THREAD

**Issue by Stepa8312** [Linaro1985/padavan-ng#8]
Since in the Dlink routers, the MAC addresses are written to a non-standard offset, I propose the following patch:
`---
 trunk/user/rc/ralink.c | 2 ++
 1 file changed, 2 insertions(+), 0 deletions(-)

diff --git a/trunk/user/rc/ralink.c b/trunk/user/rc/ralink.c
index 247847c..d2cdb5c 100644
--- a/trunk/user/rc/ralink.c
+++ b/trunk/user/rc/ralink.c
@@ -174,6 +174,8 @@ get_wired_mac_e2p_offset(int is_wan)
 {
 #if defined (BOARD_N14U) || defined (BOARD_N11P)
 	return 0x018E;
+#elif defined (BOARD_DIR300B7) || defined (BOARD_DIR320B) || defined (BOARD_DIR620D)
+	return (is_wan) ? 0x408 : 0x40E;
 #else
 	return (is_wan) ? OFFSET_MAC_GMAC2 : OFFSET_MAC_GMAC0;
 #endif
--
`

[0001-fix-read-Dlink-mac-addr-from-mtd.patch.zip](https://github.com/Linaro1985/padavan-ng/files/2256934/0001-fix-read-Dlink-mac-addr-from-mtd.patch.zip)

**Comment by Stepa8312** [comment]
Rechecked on the factory firmware - it seems I mixed LAN / WAN poppies. Must be:
 `return (is_wan)? 0x40E: 0x408;`

**Comment by Linaro1985** [comment]
Thank you! Fixed in https://github.com/Linaro1985/padavan-ng/commit/23b3c6044605b84ad639c90615ff268838e78832 . Please check the result.

**Comment by Stepa8312** [comment]
DIR620D1 - checked Ok

I checked the Factory section from the Dlink DIR300B6 / DIR300B7 / DIR320B1 / DIR620D1 - the mac addresses are located at the same offset.
But I'm not sure about the old models DIR300/DIR620 (RT3050/RT3052).
